#! /bin/sh

# setxkbmap -layout 'us,se,ir' -option grp:alt_shift_toggle &

pgrep -x dunst || dunst &

pgrep -x sxhkd > /dev/null || sxhkd &

pgrep -x picom || picom -b --experimental-backends

~/.config/bspwm/office-monitors.sh config

feh --no-fehbg --bg-fill -z $HOME/Wallpapers

xsetroot -cursor_name left_ptr

~/.config/polybar/launch.sh &

pgrep -x nm-applet > /dev/null || nm-applet &

#bspc monitor  -d 1 2 3 4 5 6 7 8 9 0

bspc config active_border_color "#F0C674"
bspc config focused_border_color "#F0C674"

bspc config border_width         4
bspc config window_gap           7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
