#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if which picom >/dev/null
then
	pgrep -x picom > /dev/null || picom &
fi

xsetroot -cursor_name left_ptr

~/.config/polybar/launch.sh &

feh --no-fehbg --bg-fill -z $HOME/Wallpapers

pgrep -x nm-applet > /dev/null || nm-applet &

setxkbmap -layout 'us,se,ir' -option grp:alt_shift_toggle &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config active_border_color "#F0C674"
bspc config focused_border_color "#F0C674"

bspc config border_width         4
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
